dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: my-sample-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.0-22
- name: sample-app-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.0-8
- name: test-actuator
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
